<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>app.voltlauncher</groupId>
        <artifactId>volt-launcher-parent</artifactId>
        <version>0.2.0</version>
    </parent>

    <artifactId>volt-game</artifactId>
    <name>VoltLauncher :: Game</name>
    <description>Instances, version resolution, mod loaders, asset installation, Java runtimes and process launching</description>

    <dependencies>
        <dependency>
            <groupId>app.voltlauncher</groupId>
            <artifactId>volt-core</artifactId>
        </dependency>
        <dependency>
            <groupId>app.voltlauncher</groupId>
            <artifactId>volt-auth</artifactId>
        </dependency>
    </dependencies>
</project>
