Args = --enable-native-access=ALL-UNNAMED \
       -Djava.awt.headless=false \
       --no-fallback \
       -O3 \
       --enable-url-protocols=https,http \
       -H:+AddAllCharsets \
       -H:+ReportExceptionStackTraces \
       --initialize-at-build-time=org.slf4j
